# Stage 1: Build the React frontend
FROM node:14 as build

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Build the React app
RUN npm run build

# Stage 2: Production environment
FROM nginx:alpine

# Copy build output from Stage 1 to nginx directory
COPY --from=build /usr/src/app/build /usr/share/nginx/html

# Copy custom nginx configuration file
COPY nginx.conf /etc/nginx/nginx.conf

# Expose port 80
EXPOSE 3000

# Start nginx to serve the frontend
CMD ["nginx", "-g", "daemon off;"]
