events {}

http {
    include mime.types;
    default_type application/octet-stream;

    server {
        listen 80;
        server_name localhost;

        # Serve the React app
        location / {
             root /usr/share/nginx/html;  # This is where the build files will be served
            index index.html;

            # This ensures that all routes will fall back to index.html file
            try_files $uri $uri/ /index.html;
        }

        # Proxy API requests to the backend (if backend is deployed)
        location /api/ {
            proxy_pass http://10.5.45.182:5000;  # Replace with actual backend address
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Handle favicon.ico and other assets
        location = /favicon.ico {
            log_not_found off;
            access_log off;
        }
    }
}
